### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by Felipefpl** [Argent77/HQ-SoundClips-BG2EE#1]
Hi, i got 3 problems with the soundclips:

1 - I couldnt install it with the content of other mods inside BG 2 folder (Luremaster was there) - i got the same error i reported with dlc-merger where windows gave me a message saying it couldnt access the files. The installation runs fine if there is no other mods with soundclips.

2 - Not sure if this was intended but in the end of the installation i get this white rectangle.
![Sem título](https://github.com/Argent77/HQ-SoundClips-BG2EE/assets/5569804/1dba264a-da85-4087-a2ea-5e85158501ca)

3 - I decided to re-install the mod just to see what would happen and i got those errors;
[SETUP-HQ_SOUNDCLIPS_BG2EE.zip](https://github.com/Argent77/HQ-SoundClips-BG2EE/files/12581226/SETUP-HQ_SOUNDCLIPS_BG2EE.zip)

I decided to make a new translation while i'm at it. :p
[brazilian portuguese.zip](https://github.com/Argent77/HQ-SoundClips-BG2EE/files/12581179/brazilian.portuguese.zip)

**Comment by Argent77** [comment]
My guess is that all these issues (read/write access errors, unable to perform WeiDU update checks, etc.) happen because you're still running Windows 7. WeiDU 248 and later were definitely aimed at more recent Windows versions.

You could try running the installers in administrator mode and see if it solves the issues (right-click on the setup file and select to run as administrator). If that doesn't work then replace all setup files with the [legacy WeiDU executable](https://github.com/WeiDUorg/weidu/releases/tag/v249.00) meant for older Windows versions and try again.

I've never seen a white region of characters in a mod installation before. Did you perhaps accidentally create a selection with the mouse cursor? A right-click on the console should fix the issue in this case.

**Comment by Argent77** [comment]
> I decided to make a new translation while i'm at it. :p

Translation has been [added](https://github.com/Argent77/HQ-SoundClips-BG2EE/commit/80fbcf7d86ef92ef9bb633f02436a5c1d5a991e5).

**Comment by Felipefpl** [comment]
> My guess is that all these issues (read/write access errors, unable to perform WeiDU update checks, etc.) happen because you're still running Windows 7. WeiDU 248 and later were definitely aimed at more recent Windows versions.

I see, that's unfortunate... :/
 
> You could try running the installers in administrator mode and see if it solves the issues (right-click on the setup file and select to run as administrator). If that doesn't work then replace all setup files with the [legacy WeiDU executable](https://github.com/WeiDUorg/weidu/releases/tag/v249.00) meant for older Windows versions and try again.

I'm an admin already so i believe it's not that. I tried to install again using project infinity and it worked without flaws which is fine and strange at the same time.
 
> I've never seen a white region of characters in a mod installation before. Did you perhaps accidentally create a selection with the mouse cursor? A right-click on the console should fix the issue in this case.

No mouse clicks there.

**Comment by Argent77** [comment]
> I'm an admin already so i believe it's not that. I tried to install again using project infinity and it worked without flaws which is fine and strange at the same time.

Did you actually try the suggested option? Afaik having an admin account and running with elevated privileges are not exactly the same. Project Infinity doesn't perform the auto-update operation when it runs a WeiDU process, which seems to be the issue here.

**Comment by Felipefpl** [comment]
Strange: i installed using admin priviledges and it worked, then i unninstalled/installed without using admin priviledges and it worked again, i dont know why i cant reproduce it.
